version: '3'
services:
  rails:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    volumes:
      - "./sample_project:/sample_project"
    ports:
      - "3000:3000"
    command: "rails s"
