version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - static-content:/var/www/app/public
      - sock-to-app:/var/www/app/tmp
    depends_on:
      - rails

  rails:
    build:
      context: .
      dockerfile: docker/rails/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - static-content:/rails/public
      - sock-to-app:/rails/tmp
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
      - RAILS_MAX_THREADS=5
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=
    command: /rails/run.sh

  db:
    image: postgres:10.5
    ports:
      - 5432:5432

volumes:
  static-content:
  sock-to-app:
